# Copyright (c) 2025-2026, The Isaac Lab Arena Project Developers (https://github.com/isaac-sim/IsaacLab-Arena/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

"""Client-side modality config for the fine-tuned GR00T N2 G1 model trained on
``nvidia/Arena-G1-Static-PickNPlace-Task``.

This mirrors the ``new_embodiment`` modality layout the N2 checkpoint
(``.../arena-g1-static-full/checkpoint-10000``) was trained with. That dataset
was generated by Arena's own G1 pipeline, so its ``meta/modality.json`` is
byte-identical to this repo's stock ``embodiments/g1/modality.json`` -- the
joint-space YAMLs (``gr00t_43dof_joint_space.yaml`` / ``43dof_joint_space.yaml``)
already match and are reused unchanged.

Arena uses the ``state`` / ``video`` / ``language`` keys on the client side to
know which observation groups to build and send to the policy server; the
``action`` block documents what the server returns and how to interpret it.

Differences vs the stock ``g1_sim_wbc_data_config.py``:
  * ``state`` includes ``left_leg`` / ``right_leg`` -- the N2 model was trained
    with full lower-body proprioception, so Arena must send leg joint state.
  * ``state`` key order is leg/leg/waist/arm/hand/arm/hand (matches the training
    config exactly), not the stock arm/arm/hand/hand.
  * ``action`` is the 5 upper-body joint groups only, all ABSOLUTE joint
    positions (the training data has no effort/relative channels), horizon 16.
"""

from gr00t.configs.data.embodiment_configs import (
    MODALITY_CONFIGS,
    register_modality_config,
)
from gr00t.data.embodiment_tags import EmbodimentTag
from gr00t.data.types import (
    ActionConfig,
    ActionFormat,
    ActionRepresentation,
    ActionType,
    ModalityConfig,
)

g1_n2_static_config = {
    "video": ModalityConfig(
        delta_indices=[0],
        modality_keys=["ego_view"],
    ),
    "state": ModalityConfig(
        delta_indices=[0],
        modality_keys=[
            "left_leg",
            "right_leg",
            "waist",
            "left_arm",
            "left_hand",
            "right_arm",
            "right_hand",
        ],
    ),
    "action": ModalityConfig(
        delta_indices=list(range(0, 16)),
        modality_keys=[
            "left_arm",
            "left_hand",
            "right_arm",
            "right_hand",
            "waist",
        ],
        action_configs=[
            ActionConfig(rep=ActionRepresentation.ABSOLUTE, type=ActionType.NON_EEF, format=ActionFormat.DEFAULT),  # left_arm
            ActionConfig(rep=ActionRepresentation.ABSOLUTE, type=ActionType.NON_EEF, format=ActionFormat.DEFAULT),  # left_hand
            ActionConfig(rep=ActionRepresentation.ABSOLUTE, type=ActionType.NON_EEF, format=ActionFormat.DEFAULT),  # right_arm
            ActionConfig(rep=ActionRepresentation.ABSOLUTE, type=ActionType.NON_EEF, format=ActionFormat.DEFAULT),  # right_hand
            ActionConfig(rep=ActionRepresentation.ABSOLUTE, type=ActionType.NON_EEF, format=ActionFormat.DEFAULT),  # waist
        ],
    ),
    "language": ModalityConfig(
        delta_indices=[0],
        modality_keys=["annotation.human.task_description"],
    ),
}

# ``register_modality_config`` asserts the tag isn't already registered, so a
# second import within the same process (pytest re-runs, notebooks) would
# crash. Re-binding is safe here -- the new config wins.
MODALITY_CONFIGS.pop(EmbodimentTag.NEW_EMBODIMENT.value, None)
register_modality_config(g1_n2_static_config, embodiment_tag=EmbodimentTag.NEW_EMBODIMENT)
